# Generated by Django 5.2.17 on 2026-09-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [("manage_domain", "Can manage domains and categories")],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                (
                    "sla_hours",
                    models.PositiveIntegerField(
                        help_text="Hours from human triage confirmation until the complaint is due."
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="domains.domain",
                    ),
                ),
            ],
            options={
                "ordering": ["domain", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "slug"), name="unique_category_slug_per_domain"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sla_hours__gt", 0)), name="sla_hours_positive"
                    ),
                ],
            },
        ),
    ]
