# Generated by Django 5.2.17 on 2026-09-03 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complaints", "0002_prediction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("status", "Status change"),
                            ("category", "Category change"),
                            ("priority", "Priority change"),
                            ("assignment", "Assignment change"),
                            ("duplicate", "Duplicate decision"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_value", models.CharField(blank=True, max_length=200, null=True)),
                ("to_value", models.CharField(blank=True, max_length=200, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaint_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="complaints.complaint",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="complaints.prediction",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["complaint", "created_at"], name="complaints__complai_131882_idx"
                    )
                ],
            },
        ),
    ]
